# Generated by Django 3.2.4 on 2021-06-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETE_KAA_SA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
