# Generated by Django 3.2.4 on 2021-06-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETE_KAA_SA', '0003_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to=None),
        ),
    ]
